### ISSUE TITLE
Printable PDF

### ISSUE THREAD

**Issue by toubar** [gto76/python-cheatsheet#20]
Would be nice to have nice printable PDF for the wall hangers enthusiasts 🥇

**Comment by hardikpnsp** [comment]
well, you can just print (Ctrl + P) the webpage.

**Comment by gto76** [comment]
PDF added.

For now I'm generating it by using copy to PDF in Chrome. It's not really an issue, because I don't intend to update it for every commit, because I don't want to inflate the size of the repo...

But it would be nice to have footers with page numbers, so a script that would use something like [html-pdf-chrome](https://github.com/westy92/html-pdf-chrome) is needed.

**Comment by toubar** [comment]
It would be nice to have for sure! Like a printable A3 wide landscape view of the best Python cheatsheet I ever found.

**Comment by gto76** [comment]
Thanks!
